#jinja2: lstrip_blocks: True
version: '2'
services:
  traefik:
    image: traefik:1.3-alpine
    command: -c /dev/null --web --docker --docker.domain={{ base_url }} --logLevel=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=traefik-backend"
      - "traefik.frontend.rule=Host:traefik.{{ base_url }}"
      - "traefik.port=8080"

{% if enable_symfony == true %}
  symfony_nginx:
    build: {{ playbook_dir }}/dockerfile/symfony_nginx
    links:
      - symfony_php:php
    volumes_from:
      - symfony_php
    labels:
      - "traefik.backend=symfony"
      - "traefik.frontend.rule=Host:symfony.{{ base_url }}"
      - "traefik.port=80"

  symfony_php:
    build: {{ playbook_dir }}/dockerfile/symfony_php{{ php_version }}
    expose:
      - "9000"
    links:
      {% if enable_mysql == true %}
      - mysql
      {% endif %}
      {% if enable_postgres == true %}
      - postgres
      {% endif %}
      {% if enable_mongodb == true %}
      - mongodb
      {% endif %}
      {% if enable_redis == true %}
      - redis
      {% endif %}
      {% if enable_rabbitmq == true %}
      - rabbitmq
      {% endif %}
      {% if enable_elasticsearch == true %}
      - elasticsearch
      {% endif %}
    volumes:
      - ":/var/www/symfony"
    labels:
      - "traefik.enable=false"
{% endif %}

{% if enable_mysql == true %}
  mysql:
    image: mysql:{{ mysql_version }}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: {{ mysql_root_password }}
    labels:
      - "traefik.enable=false"
{% endif %}

{% if enable_postgres == true %}
  postgres:
    image: postgres:{{ postgres_version }}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: {{ postgres_root_password }}
    labels:
      - "traefik.enable=false"
{% endif %}

{% if enable_redis == true %}
  redis:
    image: redis:{{ redis_version }}-alpine
    expose:
      - "6379"
    labels:
      - "traefik.enable=false"
{% endif %}

{% if enable_rabbitmq == true %}
  rabbitmq:
    image: rabbitmq:{{ rabbitmq_version }}-{% if rabbitmq_management == true %}management-{% endif %}alpine
    expose:
      - "4369"
      - "5671"
      - "5672"
    labels:
    {% if rabbitmq_management == true %}

      - "traefik.backend=rabbitmq"
      - "traefik.frontend.rule=Host:rabbitmq.{{ base_url }}"
      - "traefik.port=15672"
    {% else %}
      - "traefik.enable=false"
    {% endif %}
{% endif %}

{% if enable_mongodb == true %}
  mongodb:
    image: mongo:{{ mongodb_version }}
    expose:
      - "27017"
    labels:
      - "traefik.enable=false"
{% endif %}

{% if enable_elasticsearch == true %}
  elasticsearch:
    image: elasticsearch:{{ elasticsearch_version }}-alpine
    expose:
      - "9200"
    labels:
      - "traefik.backend=elasticsearch"
      - "traefik.frontend.rule=Host:elasticsearch.{{ base_url }}"
      - "traefik.port=9200"
{% endif %}